// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Connection-level authentication handshake messages
type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Client timestamp for replay protection
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // Client's public key (33 bytes compressed)
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                  // ECDSA signature over timestamp
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`    // Optional client identifier
	Nonce         []byte                 `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`                          // Random nonce for replay protection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HandshakeRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *HandshakeRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *HandshakeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HandshakeRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                   // Whether authentication succeeded
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                          // Error message if rejected
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Unique session identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HandshakeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Connection health check messages
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp for latency measurement
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Echo back the timestamp from Ping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Pong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// TransactionRequest represents a request of multiple transactions for a specific chain
type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       []byte                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Transaction   [][]byte               `protobuf:"bytes,2,rep,name=transaction,proto3" json:"transaction,omitempty"` // RLP encoded Ethereum transactions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionRequest) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *TransactionRequest) GetTransaction() [][]byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Cross-chain transaction request with multiple requests (one per chain)
type XTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionRequest  `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XTRequest) Reset() {
	*x = XTRequest{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XTRequest) ProtoMessage() {}

func (x *XTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XTRequest.ProtoReflect.Descriptor instead.
func (*XTRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *XTRequest) GetTransactions() []*TransactionRequest {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// Message to start cross-chain transaction coordination
type StartInstance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     []byte                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`              // Unique instance ID
	PeriodId       uint64                 `protobuf:"varint,2,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`                   // Current period ID
	SequenceNumber uint64                 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // Sequence number for ordering within the period
	XtRequest      *XTRequest             `protobuf:"bytes,4,opt,name=xt_request,json=xtRequest,proto3" json:"xt_request,omitempty"`                 // The cross-chain transaction request
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartInstance) Reset() {
	*x = StartInstance{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstance) ProtoMessage() {}

func (x *StartInstance) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstance.ProtoReflect.Descriptor instead.
func (*StartInstance) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *StartInstance) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *StartInstance) GetPeriodId() uint64 {
	if x != nil {
		return x.PeriodId
	}
	return 0
}

func (x *StartInstance) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *StartInstance) GetXtRequest() *XTRequest {
	if x != nil {
		return x.XtRequest
	}
	return nil
}

// 2PC Vote message from a sequencer to the SP
type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    []byte                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Instance ID
	ChainId       uint64                 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`         // Which chain is voting
	Vote          bool                   `protobuf:"varint,3,opt,name=vote,proto3" json:"vote,omitempty"`                              // true = Commit, false = Abort
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Vote) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *Vote) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Vote) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

// 2PC Decision message from the SP to sequencers
type Decided struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    []byte                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Instance ID
	Decision      bool                   `protobuf:"varint,2,opt,name=decision,proto3" json:"decision,omitempty"`                      // true = Commit, false = Abort
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decided) Reset() {
	*x = Decided{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decided) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decided) ProtoMessage() {}

func (x *Decided) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decided.ProtoReflect.Descriptor instead.
func (*Decided) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Decided) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *Decided) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

// Direct Mailbox message exchange between sequencers (without SP involvement)
type MailboxMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InstanceId       []byte                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Instance ID
	SourceChain      uint64                 `protobuf:"varint,2,opt,name=source_chain,json=sourceChain,proto3" json:"source_chain,omitempty"`
	DestinationChain uint64                 `protobuf:"varint,3,opt,name=destination_chain,json=destinationChain,proto3" json:"destination_chain,omitempty"`
	Source           []byte                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Receiver         []byte                 `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	SessionId        uint64                 `protobuf:"varint,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Label            string                 `protobuf:"bytes,7,opt,name=label,proto3" json:"label,omitempty"`
	Data             [][]byte               `protobuf:"bytes,8,rep,name=data,proto3" json:"data,omitempty"` // ABI encoded data
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MailboxMessage) Reset() {
	*x = MailboxMessage{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailboxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailboxMessage) ProtoMessage() {}

func (x *MailboxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailboxMessage.ProtoReflect.Descriptor instead.
func (*MailboxMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *MailboxMessage) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *MailboxMessage) GetSourceChain() uint64 {
	if x != nil {
		return x.SourceChain
	}
	return 0
}

func (x *MailboxMessage) GetDestinationChain() uint64 {
	if x != nil {
		return x.DestinationChain
	}
	return 0
}

func (x *MailboxMessage) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *MailboxMessage) GetReceiver() []byte {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *MailboxMessage) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *MailboxMessage) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MailboxMessage) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Message sent by SP to start a new period
type StartPeriod struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PeriodId         uint64                 `protobuf:"varint,1,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`                         // New period id
	SuperblockNumber uint64                 `protobuf:"varint,2,opt,name=superblock_number,json=superblockNumber,proto3" json:"superblock_number,omitempty"` // Superblock number SP aims to produce
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartPeriod) Reset() {
	*x = StartPeriod{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPeriod) ProtoMessage() {}

func (x *StartPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPeriod.ProtoReflect.Descriptor instead.
func (*StartPeriod) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *StartPeriod) GetPeriodId() uint64 {
	if x != nil {
		return x.PeriodId
	}
	return 0
}

func (x *StartPeriod) GetSuperblockNumber() uint64 {
	if x != nil {
		return x.SuperblockNumber
	}
	return 0
}

// Message sent by SP to rollback and restart from a valid state
type Rollback struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	PeriodId                      uint64                 `protobuf:"varint,1,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`                                                                    // Current period id
	LastFinalizedSuperblockNumber uint64                 `protobuf:"varint,2,opt,name=last_finalized_superblock_number,json=lastFinalizedSuperblockNumber,proto3" json:"last_finalized_superblock_number,omitempty"` // Last finalized superblock number
	LastFinalizedSuperblockHash   []byte                 `protobuf:"bytes,3,opt,name=last_finalized_superblock_hash,json=lastFinalizedSuperblockHash,proto3" json:"last_finalized_superblock_hash,omitempty"`        // Last finalized superblock hash
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Rollback) Reset() {
	*x = Rollback{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rollback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rollback) ProtoMessage() {}

func (x *Rollback) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rollback.ProtoReflect.Descriptor instead.
func (*Rollback) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *Rollback) GetPeriodId() uint64 {
	if x != nil {
		return x.PeriodId
	}
	return 0
}

func (x *Rollback) GetLastFinalizedSuperblockNumber() uint64 {
	if x != nil {
		return x.LastFinalizedSuperblockNumber
	}
	return 0
}

func (x *Rollback) GetLastFinalizedSuperblockHash() []byte {
	if x != nil {
		return x.LastFinalizedSuperblockHash
	}
	return nil
}

// SP sends to the WS after collecting votes
type NativeDecided struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    []byte                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Decision      bool                   `protobuf:"varint,2,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NativeDecided) Reset() {
	*x = NativeDecided{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeDecided) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeDecided) ProtoMessage() {}

func (x *NativeDecided) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeDecided.ProtoReflect.Descriptor instead.
func (*NativeDecided) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *NativeDecided) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *NativeDecided) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

// WS sends to the SP after getting the response from ER client
type WSDecided struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    []byte                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Decision      bool                   `protobuf:"varint,2,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSDecided) Reset() {
	*x = WSDecided{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSDecided) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSDecided) ProtoMessage() {}

func (x *WSDecided) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSDecided.ProtoReflect.Descriptor instead.
func (*WSDecided) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *WSDecided) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *WSDecided) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

// Wrapper for all messages
type Message struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // Identifier of the sender
	// Payload contains the actual message content
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_HandshakeRequest
	//	*Message_HandshakeResponse
	//	*Message_Ping
	//	*Message_Pong
	//	*Message_XtRequest
	//	*Message_StartInstance
	//	*Message_Vote
	//	*Message_Decided
	//	*Message_MailboxMessage
	//	*Message_StartPeriod
	//	*Message_Rollback
	//	*Message_NativeDecided
	//	*Message_WsDecided
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetHandshakeRequest() *HandshakeRequest {
	if x != nil {
		if x, ok := x.Payload.(*Message_HandshakeRequest); ok {
			return x.HandshakeRequest
		}
	}
	return nil
}

func (x *Message) GetHandshakeResponse() *HandshakeResponse {
	if x != nil {
		if x, ok := x.Payload.(*Message_HandshakeResponse); ok {
			return x.HandshakeResponse
		}
	}
	return nil
}

func (x *Message) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*Message_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Message) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*Message_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Message) GetXtRequest() *XTRequest {
	if x != nil {
		if x, ok := x.Payload.(*Message_XtRequest); ok {
			return x.XtRequest
		}
	}
	return nil
}

func (x *Message) GetStartInstance() *StartInstance {
	if x != nil {
		if x, ok := x.Payload.(*Message_StartInstance); ok {
			return x.StartInstance
		}
	}
	return nil
}

func (x *Message) GetVote() *Vote {
	if x != nil {
		if x, ok := x.Payload.(*Message_Vote); ok {
			return x.Vote
		}
	}
	return nil
}

func (x *Message) GetDecided() *Decided {
	if x != nil {
		if x, ok := x.Payload.(*Message_Decided); ok {
			return x.Decided
		}
	}
	return nil
}

func (x *Message) GetMailboxMessage() *MailboxMessage {
	if x != nil {
		if x, ok := x.Payload.(*Message_MailboxMessage); ok {
			return x.MailboxMessage
		}
	}
	return nil
}

func (x *Message) GetStartPeriod() *StartPeriod {
	if x != nil {
		if x, ok := x.Payload.(*Message_StartPeriod); ok {
			return x.StartPeriod
		}
	}
	return nil
}

func (x *Message) GetRollback() *Rollback {
	if x != nil {
		if x, ok := x.Payload.(*Message_Rollback); ok {
			return x.Rollback
		}
	}
	return nil
}

func (x *Message) GetNativeDecided() *NativeDecided {
	if x != nil {
		if x, ok := x.Payload.(*Message_NativeDecided); ok {
			return x.NativeDecided
		}
	}
	return nil
}

func (x *Message) GetWsDecided() *WSDecided {
	if x != nil {
		if x, ok := x.Payload.(*Message_WsDecided); ok {
			return x.WsDecided
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_HandshakeRequest struct {
	// Connection-level authentication
	HandshakeRequest *HandshakeRequest `protobuf:"bytes,2,opt,name=handshake_request,json=handshakeRequest,proto3,oneof"`
}

type Message_HandshakeResponse struct {
	HandshakeResponse *HandshakeResponse `protobuf:"bytes,3,opt,name=handshake_response,json=handshakeResponse,proto3,oneof"`
}

type Message_Ping struct {
	// Connection health check
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type Message_Pong struct {
	Pong *Pong `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

type Message_XtRequest struct {
	// SCP
	XtRequest *XTRequest `protobuf:"bytes,6,opt,name=xt_request,json=xtRequest,proto3,oneof"`
}

type Message_StartInstance struct {
	StartInstance *StartInstance `protobuf:"bytes,7,opt,name=start_instance,json=startInstance,proto3,oneof"`
}

type Message_Vote struct {
	Vote *Vote `protobuf:"bytes,8,opt,name=vote,proto3,oneof"`
}

type Message_Decided struct {
	Decided *Decided `protobuf:"bytes,9,opt,name=decided,proto3,oneof"`
}

type Message_MailboxMessage struct {
	MailboxMessage *MailboxMessage `protobuf:"bytes,10,opt,name=mailbox_message,json=mailboxMessage,proto3,oneof"`
}

type Message_StartPeriod struct {
	// SBCP messages
	StartPeriod *StartPeriod `protobuf:"bytes,11,opt,name=start_period,json=startPeriod,proto3,oneof"`
}

type Message_Rollback struct {
	Rollback *Rollback `protobuf:"bytes,12,opt,name=rollback,proto3,oneof"`
}

type Message_NativeDecided struct {
	// CDCP
	NativeDecided *NativeDecided `protobuf:"bytes,13,opt,name=native_decided,json=nativeDecided,proto3,oneof"`
}

type Message_WsDecided struct {
	WsDecided *WSDecided `protobuf:"bytes,14,opt,name=ws_decided,json=wsDecided,proto3,oneof"`
}

func (*Message_HandshakeRequest) isMessage_Payload() {}

func (*Message_HandshakeResponse) isMessage_Payload() {}

func (*Message_Ping) isMessage_Payload() {}

func (*Message_Pong) isMessage_Payload() {}

func (*Message_XtRequest) isMessage_Payload() {}

func (*Message_StartInstance) isMessage_Payload() {}

func (*Message_Vote) isMessage_Payload() {}

func (*Message_Decided) isMessage_Payload() {}

func (*Message_MailboxMessage) isMessage_Payload() {}

func (*Message_StartPeriod) isMessage_Payload() {}

func (*Message_Rollback) isMessage_Payload() {}

func (*Message_NativeDecided) isMessage_Payload() {}

func (*Message_WsDecided) isMessage_Payload() {}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\acompose\"\xa0\x01\n" +
	"\x10HandshakeRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\fR\x05nonce\"d\n" +
	"\x11HandshakeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"Q\n" +
	"\x12TransactionRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\fR\achainId\x12 \n" +
	"\vtransaction\x18\x02 \x03(\fR\vtransaction\"L\n" +
	"\tXTRequest\x12?\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1b.compose.TransactionRequestR\ftransactions\"\xa9\x01\n" +
	"\rStartInstance\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\fR\n" +
	"instanceId\x12\x1b\n" +
	"\tperiod_id\x18\x02 \x01(\x04R\bperiodId\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x04R\x0esequenceNumber\x121\n" +
	"\n" +
	"xt_request\x18\x04 \x01(\v2\x12.compose.XTRequestR\txtRequest\"V\n" +
	"\x04Vote\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\fR\n" +
	"instanceId\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\x12\x12\n" +
	"\x04vote\x18\x03 \x01(\bR\x04vote\"F\n" +
	"\aDecided\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\fR\n" +
	"instanceId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\bR\bdecision\"\xfe\x01\n" +
	"\x0eMailboxMessage\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\fR\n" +
	"instanceId\x12!\n" +
	"\fsource_chain\x18\x02 \x01(\x04R\vsourceChain\x12+\n" +
	"\x11destination_chain\x18\x03 \x01(\x04R\x10destinationChain\x12\x16\n" +
	"\x06source\x18\x04 \x01(\fR\x06source\x12\x1a\n" +
	"\breceiver\x18\x05 \x01(\fR\breceiver\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\x04R\tsessionId\x12\x14\n" +
	"\x05label\x18\a \x01(\tR\x05label\x12\x12\n" +
	"\x04data\x18\b \x03(\fR\x04data\"W\n" +
	"\vStartPeriod\x12\x1b\n" +
	"\tperiod_id\x18\x01 \x01(\x04R\bperiodId\x12+\n" +
	"\x11superblock_number\x18\x02 \x01(\x04R\x10superblockNumber\"\xb5\x01\n" +
	"\bRollback\x12\x1b\n" +
	"\tperiod_id\x18\x01 \x01(\x04R\bperiodId\x12G\n" +
	" last_finalized_superblock_number\x18\x02 \x01(\x04R\x1dlastFinalizedSuperblockNumber\x12C\n" +
	"\x1elast_finalized_superblock_hash\x18\x03 \x01(\fR\x1blastFinalizedSuperblockHash\"L\n" +
	"\rNativeDecided\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\fR\n" +
	"instanceId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\bR\bdecision\"H\n" +
	"\tWSDecided\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\fR\n" +
	"instanceId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\bR\bdecision\"\x81\x06\n" +
	"\aMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12H\n" +
	"\x11handshake_request\x18\x02 \x01(\v2\x19.compose.HandshakeRequestH\x00R\x10handshakeRequest\x12K\n" +
	"\x12handshake_response\x18\x03 \x01(\v2\x1a.compose.HandshakeResponseH\x00R\x11handshakeResponse\x12#\n" +
	"\x04ping\x18\x04 \x01(\v2\r.compose.PingH\x00R\x04ping\x12#\n" +
	"\x04pong\x18\x05 \x01(\v2\r.compose.PongH\x00R\x04pong\x123\n" +
	"\n" +
	"xt_request\x18\x06 \x01(\v2\x12.compose.XTRequestH\x00R\txtRequest\x12?\n" +
	"\x0estart_instance\x18\a \x01(\v2\x16.compose.StartInstanceH\x00R\rstartInstance\x12#\n" +
	"\x04vote\x18\b \x01(\v2\r.compose.VoteH\x00R\x04vote\x12,\n" +
	"\adecided\x18\t \x01(\v2\x10.compose.DecidedH\x00R\adecided\x12B\n" +
	"\x0fmailbox_message\x18\n" +
	" \x01(\v2\x17.compose.MailboxMessageH\x00R\x0emailboxMessage\x129\n" +
	"\fstart_period\x18\v \x01(\v2\x14.compose.StartPeriodH\x00R\vstartPeriod\x12/\n" +
	"\brollback\x18\f \x01(\v2\x11.compose.RollbackH\x00R\brollback\x12?\n" +
	"\x0enative_decided\x18\r \x01(\v2\x16.compose.NativeDecidedH\x00R\rnativeDecided\x123\n" +
	"\n" +
	"ws_decided\x18\x0e \x01(\v2\x12.compose.WSDecidedH\x00R\twsDecidedB\t\n" +
	"\apayloadB0Z.github.com/compose-network/specs/compose/protob\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_messages_proto_goTypes = []any{
	(*HandshakeRequest)(nil),   // 0: compose.HandshakeRequest
	(*HandshakeResponse)(nil),  // 1: compose.HandshakeResponse
	(*Ping)(nil),               // 2: compose.Ping
	(*Pong)(nil),               // 3: compose.Pong
	(*TransactionRequest)(nil), // 4: compose.TransactionRequest
	(*XTRequest)(nil),          // 5: compose.XTRequest
	(*StartInstance)(nil),      // 6: compose.StartInstance
	(*Vote)(nil),               // 7: compose.Vote
	(*Decided)(nil),            // 8: compose.Decided
	(*MailboxMessage)(nil),     // 9: compose.MailboxMessage
	(*StartPeriod)(nil),        // 10: compose.StartPeriod
	(*Rollback)(nil),           // 11: compose.Rollback
	(*NativeDecided)(nil),      // 12: compose.NativeDecided
	(*WSDecided)(nil),          // 13: compose.WSDecided
	(*Message)(nil),            // 14: compose.Message
}
var file_messages_proto_depIdxs = []int32{
	4,  // 0: compose.XTRequest.transactions:type_name -> compose.TransactionRequest
	5,  // 1: compose.StartInstance.xt_request:type_name -> compose.XTRequest
	0,  // 2: compose.Message.handshake_request:type_name -> compose.HandshakeRequest
	1,  // 3: compose.Message.handshake_response:type_name -> compose.HandshakeResponse
	2,  // 4: compose.Message.ping:type_name -> compose.Ping
	3,  // 5: compose.Message.pong:type_name -> compose.Pong
	5,  // 6: compose.Message.xt_request:type_name -> compose.XTRequest
	6,  // 7: compose.Message.start_instance:type_name -> compose.StartInstance
	7,  // 8: compose.Message.vote:type_name -> compose.Vote
	8,  // 9: compose.Message.decided:type_name -> compose.Decided
	9,  // 10: compose.Message.mailbox_message:type_name -> compose.MailboxMessage
	10, // 11: compose.Message.start_period:type_name -> compose.StartPeriod
	11, // 12: compose.Message.rollback:type_name -> compose.Rollback
	12, // 13: compose.Message.native_decided:type_name -> compose.NativeDecided
	13, // 14: compose.Message.ws_decided:type_name -> compose.WSDecided
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[14].OneofWrappers = []any{
		(*Message_HandshakeRequest)(nil),
		(*Message_HandshakeResponse)(nil),
		(*Message_Ping)(nil),
		(*Message_Pong)(nil),
		(*Message_XtRequest)(nil),
		(*Message_StartInstance)(nil),
		(*Message_Vote)(nil),
		(*Message_Decided)(nil),
		(*Message_MailboxMessage)(nil),
		(*Message_StartPeriod)(nil),
		(*Message_Rollback)(nil),
		(*Message_NativeDecided)(nil),
		(*Message_WsDecided)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
